---
abstract: 'Interface to the BME280 AT/RH/BP sensor'
author:
  - 'Mark Hinds <zoro98020@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  RPi::I2C: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RPi-BME280
no_index:
  directory:
    - t
    - inc
requires:
  Event: '1.27'
  RPi::I2C: '2.3608'
  perl: '5.006'
version: '0.0001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
